### ISSUE TITLE
conflict with mock.patch

### ISSUE THREAD

**Issue by mpagot** [aklajnert/pytest-subprocess#82] opened 2022-05-31 12:51 UTC
I have a script that internally is using *subproccess.run* to call some external executable (e.g *dosomething*). 
So for example
```
$ python myscript.py do
```
It internally results in a subprocess call of `dosomething /tmp`
Test about this base functionality is like
```
def test_main(fp):
    fp.register(['dosomething', '/tmp'])
    main(['do'])
```

Some of the script configurations (sort of hidden) are using env variables. So for example
```
$ MYSCRIPT_TMP_FOLDER=/mytmp  python myscript.py do
```
It internally results in a subprocess call of `dosomething /mytmp`

My attempt to test it is like
```
def test_main(fp):
    fp.register(['dosomething', '/mytmp'])
    with mock.patch.dict(os.environ, {'MYSCRIPT_TMP_FOLDER': 'mytmp'}):
        main(['do'])
```
Unfortunately the *with mock* (or something else) seems to interfere with fp. As result the true subprocess and so the dosomething executable is called during the test.

Expected behavior is that fp to keep to be able to intercept submodule call and not to perform it.

**Comment by aklajnert** [comment] 2022-06-16 07:55
Sorry @mpagot, but I'm not able to reproduce this issue. Here's how I've tried it:
```python
COMMAND = ["dosomething", "/mytmp"]


def subprocess_calling_function(_):
    subprocess.call(COMMAND)


def test_mock_interference(fp):

    fp.allow_unregistered(False)

    fp.register(COMMAND)
    with mock.patch.dict(os.environ, {"MYSCRIPT_TMP_FOLDER": "mytmp"}):
        subprocess_calling_function(COMMAND)

    assert fp.call_count(COMMAND) == 1
```

Please provide a minimal example that reproduces the problem, otherwise, I cannot fix this.

**Comment by aklajnert** [comment] 2022-10-02 07:09
Closing this issue as it cannot be reproduced. Feel free to reopen when you'll be able to provide a method to reproduce this problem.

**Closed by aklajnert** 2022-10-02 07:09 UTC
